apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user 
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: konda2srikanth/test:user2.0
        ports:
        - containerPort: 8080
        envFrom: 
          - configMapRef: 
              name: user-cm 

--- 
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
  - name: user-port
    protocol: TCP
    port: 8080
    targetPort: 8080
